import {
  argbFromHex,
  hexFromArgb,
  MaterialDynamicColors,
  SchemeFidelity,
  Hct,
} from '@material/material-color-utilities'

declare const seedColourBrand: unique symbol

/** A `#rrggbb` colour the whole M3 scheme is derived from. */
export type SeedColour = string & { readonly [seedColourBrand]: true }

export function isSeedColour(value: string): value is SeedColour {
  return /^#[0-9a-f]{6}$/i.test(value)
}

export function seedColour(value: string): SeedColour {
  if (!isSeedColour(value)) throw new Error(`Not a #rrggbb seed colour: ${JSON.stringify(value)}`)
  return value
}

/** The M3 colour roles the app may use, in the order they are emitted. */
export const colourRoleNames = [
  'primary', 'onPrimary', 'primaryContainer', 'onPrimaryContainer',
  'secondary', 'onSecondary', 'secondaryContainer', 'onSecondaryContainer',
  'tertiary', 'onTertiary', 'tertiaryContainer', 'onTertiaryContainer',
  'error', 'onError', 'errorContainer', 'onErrorContainer',
  'background', 'onBackground',
  'surface', 'onSurface', 'surfaceVariant', 'onSurfaceVariant',
  'outline', 'outlineVariant', 'shadow', 'scrim',
  'inverseSurface', 'inverseOnSurface', 'inversePrimary',
  'surfaceDim', 'surfaceBright',
  'surfaceContainerLowest', 'surfaceContainerLow', 'surfaceContainer',
  'surfaceContainerHigh', 'surfaceContainerHighest',
  'surfaceTint',
  'primaryFixed', 'primaryFixedDim', 'onPrimaryFixed', 'onPrimaryFixedVariant',
  'secondaryFixed', 'secondaryFixedDim', 'onSecondaryFixed', 'onSecondaryFixedVariant',
  'tertiaryFixed', 'tertiaryFixedDim', 'onTertiaryFixed', 'onTertiaryFixedVariant',
] as const

export type ColourRoleName = (typeof colourRoleNames)[number]

/** `surfaceContainerHigh` → `--md-sys-color-surface-container-high`. */
export function colourRoleProperty(role: ColourRoleName): string {
  return `--md-sys-color-${role.replace(/[A-Z]/g, (c) => `-${c.toLowerCase()}`)}`
}

/** The `#rrggbb` a colour role takes in the light or dark scheme derived from `seed`. */
export function colourRoleHex(seed: SeedColour, role: ColourRoleName, isDark: boolean): string {
  return roleHex(scheme(seed, isDark), role)
}

function scheme(seed: SeedColour, isDark: boolean): SchemeFidelity {
  return new SchemeFidelity(Hct.fromInt(argbFromHex(seed)), isDark, 0)
}

function roleHex(derived: SchemeFidelity, role: ColourRoleName): string {
  return hexFromArgb(MaterialDynamicColors[role].getArgb(derived))
}

function declarations(seed: SeedColour, isDark: boolean): string {
  const derived = scheme(seed, isDark)
  return colourRoleNames
    .map((role) => `  ${colourRoleProperty(role)}: ${roleHex(derived, role)};`)
    .join('\n')
}

/** The contents of `theme.css`: light roles on `:root`, dark roles under `prefers-color-scheme`. */
export function colourRolesCss(seed: SeedColour): string {
  return [
    '/* Generated by `npm run theme` from `themeColor` in src/theme.ts. Do not edit. */',
    ':root {',
    '  color-scheme: light dark;',
    declarations(seed, false),
    '}',
    '',
    '@media (prefers-color-scheme: dark) {',
    '  :root {',
    declarations(seed, true).replace(/^/gm, '  '),
    '  }',
    '}',
    '',
  ].join('\n')
}
